// @generated
// This file is @generated by prost-build.
// =============================================================================
// Loglyph queries
// =============================================================================

/// GetLoglyphRequest queries client debug log entries.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetLoglyphRequest {
    /// log_stream_id is the PublicID (SHA-256 of PrivateID) to query.
    #[prost(string, tag = "1")]
    pub log_stream_id: ::prost::alloc::string::String,
    /// from is the start of the time range (inclusive).
    #[prost(message, optional, tag = "2")]
    pub from: ::core::option::Option<::prost_types::Timestamp>,
    /// to is the end of the time range (exclusive).
    #[prost(message, optional, tag = "3")]
    pub to: ::core::option::Option<::prost_types::Timestamp>,
    /// limit is the maximum number of entries to return.
    #[prost(int32, tag = "4")]
    pub limit: i32,
    /// offset is the number of entries to skip (for pagination).
    #[prost(int32, tag = "5")]
    pub offset: i32,
    /// session_id is an optional filter to restrict results to a single session.
    #[prost(string, tag = "6")]
    pub session_id: ::prost::alloc::string::String,
    /// level is an optional filter for log level (e.g., "error", "warn").
    #[prost(string, tag = "7")]
    pub level: ::prost::alloc::string::String,
    /// telemetry_log_id is the server-provided node-level telemetry ID for admin queries.
    /// If set, queries entries by this ID instead of log_stream_id.
    #[prost(string, tag = "8")]
    pub telemetry_log_id: ::prost::alloc::string::String,
}
/// GetLoglyphResponse contains the queried log entries.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetLoglyphResponse {
    /// entries is the list of log entries matching the query.
    #[prost(message, repeated, tag = "1")]
    pub entries: ::prost::alloc::vec::Vec<StoredLoglyphEntry>,
    /// total_count is the total number of matching entries (for pagination).
    #[prost(int64, tag = "2")]
    pub total_count: i64,
}
/// StoredLoglyphEntry is a log entry as stored in the database.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StoredLoglyphEntry {
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(string, tag = "2")]
    pub log_stream_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub client_version: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "5")]
    pub client_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "6")]
    pub received_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag = "7")]
    pub level: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub text: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub payload: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "10")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    /// telemetry_log_id is the server-provided node-level ID for admin correlation.
    #[prost(string, tag = "11")]
    pub telemetry_log_id: ::prost::alloc::string::String,
}
// =============================================================================
// Orbit queries
// =============================================================================

/// GetOrbitEventsRequest queries stored telemetry events.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetOrbitEventsRequest {
    /// log_stream_id is the PublicID to query.
    #[prost(string, tag = "1")]
    pub log_stream_id: ::prost::alloc::string::String,
    /// session_id is an optional filter for a specific session.
    #[prost(string, tag = "2")]
    pub session_id: ::prost::alloc::string::String,
    /// from is the start of the time range (inclusive).
    #[prost(message, optional, tag = "3")]
    pub from: ::core::option::Option<::prost_types::Timestamp>,
    /// to is the end of the time range (exclusive).
    #[prost(message, optional, tag = "4")]
    pub to: ::core::option::Option<::prost_types::Timestamp>,
    /// limit is the maximum number of events to return.
    #[prost(int32, tag = "5")]
    pub limit: i32,
    /// offset is the number of events to skip (for pagination).
    #[prost(int32, tag = "6")]
    pub offset: i32,
    /// payload_type is an optional filter (e.g., "send_result", "path_transition").
    #[prost(string, tag = "7")]
    pub payload_type: ::prost::alloc::string::String,
    /// telemetry_log_id is the server-provided node-level telemetry ID for admin queries.
    /// If set, queries events by this ID instead of log_stream_id.
    #[prost(string, tag = "8")]
    pub telemetry_log_id: ::prost::alloc::string::String,
}
/// GetOrbitEventsResponse contains the queried events.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetOrbitEventsResponse {
    /// events is the list of events matching the query.
    #[prost(message, repeated, tag = "1")]
    pub events: ::prost::alloc::vec::Vec<StoredOrbitEvent>,
    /// total_count is the total number of matching events (for pagination).
    #[prost(int64, tag = "2")]
    pub total_count: i64,
}
/// StoredOrbitEvent is a telemetry event as stored in the database.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StoredOrbitEvent {
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(string, tag = "2")]
    pub log_stream_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub client_version: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "5")]
    pub received_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "6")]
    pub event_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "7")]
    pub event_day: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(bytes = "vec", tag = "8")]
    pub peer_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag = "9")]
    pub region_id: u32,
    #[prost(int32, tag = "10")]
    pub transport: i32,
    #[prost(string, tag = "11")]
    pub payload_type: ::prost::alloc::string::String,
    /// JSON-encoded payload
    #[prost(string, tag = "12")]
    pub payload: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "13")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    /// telemetry_log_id is the server-provided node-level ID for admin correlation.
    #[prost(string, tag = "14")]
    pub telemetry_log_id: ::prost::alloc::string::String,
}
/// GetOrbitDailyCountsRequest queries aggregated daily telemetry counts.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetOrbitDailyCountsRequest {
    /// log_stream_id is the PublicID to query.
    #[prost(string, tag = "1")]
    pub log_stream_id: ::prost::alloc::string::String,
    /// metric is an optional filter for a specific metric name.
    #[prost(string, tag = "2")]
    pub metric: ::prost::alloc::string::String,
    /// from is the start of the time range (inclusive).
    #[prost(message, optional, tag = "3")]
    pub from: ::core::option::Option<::prost_types::Timestamp>,
    /// to is the end of the time range (exclusive).
    #[prost(message, optional, tag = "4")]
    pub to: ::core::option::Option<::prost_types::Timestamp>,
}
/// GetOrbitDailyCountsResponse contains the aggregated counts.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetOrbitDailyCountsResponse {
    /// counts is the list of daily counts matching the query.
    #[prost(message, repeated, tag = "1")]
    pub counts: ::prost::alloc::vec::Vec<DailyCount>,
}
/// DailyCount represents an aggregated count for a day.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DailyCount {
    #[prost(message, optional, tag = "1")]
    pub day: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag = "2")]
    pub log_stream_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub metric: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub label_key: ::prost::alloc::string::String,
    #[prost(int64, tag = "5")]
    pub count: i64,
    #[prost(message, optional, tag = "6")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "7")]
    pub updated_at: ::core::option::Option<::prost_types::Timestamp>,
}
// =============================================================================
// PacketFlowLog queries
// =============================================================================

/// GetPacketFlowLogsRequest queries network flow statistics.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetPacketFlowLogsRequest {
    /// log_stream_id is the PublicID to query.
    #[prost(string, tag = "1")]
    pub log_stream_id: ::prost::alloc::string::String,
    /// from is the start of the time range (inclusive).
    #[prost(message, optional, tag = "2")]
    pub from: ::core::option::Option<::prost_types::Timestamp>,
    /// to is the end of the time range (exclusive).
    #[prost(message, optional, tag = "3")]
    pub to: ::core::option::Option<::prost_types::Timestamp>,
    /// limit is the maximum number of records to return.
    #[prost(int32, tag = "4")]
    pub limit: i32,
    /// offset is the number of records to skip (for pagination).
    #[prost(int32, tag = "5")]
    pub offset: i32,
    /// node_type is an optional filter (e.g., "peer", "lan", "exit", "transport").
    #[prost(string, tag = "6")]
    pub node_type: ::prost::alloc::string::String,
    /// domain_telemetry_log_id is the server-provided tenant-level telemetry ID for admin queries.
    /// If set, queries logs by this ID instead of log_stream_id.
    #[prost(string, tag = "7")]
    pub domain_telemetry_log_id: ::prost::alloc::string::String,
    /// telemetry_log_id is the server-provided node-level telemetry ID for per-node queries.
    /// Priority: domain_telemetry_log_id > telemetry_log_id > log_stream_id.
    #[prost(string, tag = "8")]
    pub telemetry_log_id: ::prost::alloc::string::String,
}
/// GetPacketFlowLogsResponse contains the queried flow logs.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPacketFlowLogsResponse {
    /// logs is the list of flow records matching the query.
    #[prost(message, repeated, tag = "1")]
    pub logs: ::prost::alloc::vec::Vec<StoredPacketFlowLog>,
    /// total_count is the total number of matching records (for pagination).
    #[prost(int64, tag = "2")]
    pub total_count: i64,
}
/// StoredPacketFlowLog is a flow record as stored in the database.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StoredPacketFlowLog {
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(string, tag = "2")]
    pub log_stream_id: ::prost::alloc::string::String,
    /// peer/lan/exit/transport
    #[prost(string, tag = "3")]
    pub node_type: ::prost::alloc::string::String,
    /// tcp/udp/icmpv4/icmpv6
    #[prost(string, tag = "4")]
    pub protocol: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub src_ip: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub dst_ip: ::prost::alloc::string::String,
    #[prost(uint64, tag = "7")]
    pub tx_packets: u64,
    #[prost(uint64, tag = "8")]
    pub tx_bytes: u64,
    #[prost(uint64, tag = "9")]
    pub rx_packets: u64,
    #[prost(uint64, tag = "10")]
    pub rx_bytes: u64,
    #[prost(message, optional, tag = "11")]
    pub started_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "12")]
    pub ended_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "13")]
    pub logged_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "14")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    /// domain_telemetry_log_id is the server-provided tenant-level ID for admin correlation.
    #[prost(string, tag = "15")]
    pub domain_telemetry_log_id: ::prost::alloc::string::String,
    /// Source node identity (A-plan: embedded in payload for self-contained SIEM export).
    ///
    /// per-node UUID
    #[prost(string, tag = "16")]
    pub telemetry_log_id: ::prost::alloc::string::String,
    /// source hostname (e.g. "alice-macbook.runep9anv.runet.")
    #[prost(string, tag = "17")]
    pub node_name: ::prost::alloc::string::String,
    /// source user email (e.g. "alice@example.com")
    #[prost(string, tag = "18")]
    pub user_email: ::prost::alloc::string::String,
    /// Destination node identity (resolved from dst_peers, Tailscale-style deduplication).
    /// Only populated for peer traffic (Runetale IP <-> Runetale IP).
    ///
    /// destination hostname
    #[prost(string, tag = "19")]
    pub dst_node_name: ::prost::alloc::string::String,
    /// destination user email
    #[prost(string, tag = "20")]
    pub dst_user_email: ::prost::alloc::string::String,
    /// destination node ID
    #[prost(string, tag = "21")]
    pub dst_node_id: ::prost::alloc::string::String,
}
// =============================================================================
// Single tenant traffic summary
// =============================================================================

/// GetTenantTrafficSummaryRequest queries aggregated traffic for a single tenant.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetTenantTrafficSummaryRequest {
    /// domain_telemetry_log_id is the tenant-level telemetry ID (from tenant_specs).
    #[prost(string, tag = "1")]
    pub domain_telemetry_log_id: ::prost::alloc::string::String,
    /// from is the start of the time range (inclusive). Defaults to 30 days ago if unset.
    #[prost(message, optional, tag = "2")]
    pub from: ::core::option::Option<::prost_types::Timestamp>,
    /// to is the end of the time range (exclusive). Defaults to now if unset.
    #[prost(message, optional, tag = "3")]
    pub to: ::core::option::Option<::prost_types::Timestamp>,
}
/// GetTenantTrafficSummaryResponse contains the aggregated traffic for a tenant.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetTenantTrafficSummaryResponse {
    /// domain_telemetry_log_id is the queried tenant-level telemetry ID.
    #[prost(string, tag = "1")]
    pub domain_telemetry_log_id: ::prost::alloc::string::String,
    /// total_tx_bytes is the total transmitted bytes in the time range.
    #[prost(int64, tag = "2")]
    pub total_tx_bytes: i64,
    /// total_rx_bytes is the total received bytes in the time range.
    #[prost(int64, tag = "3")]
    pub total_rx_bytes: i64,
    /// total_bytes is the sum of tx + rx bytes.
    #[prost(int64, tag = "4")]
    pub total_bytes: i64,
}
// =============================================================================
// Batch tenant traffic summaries
// =============================================================================

/// GetTenantTrafficSummariesRequest queries aggregated traffic for multiple tenants.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetTenantTrafficSummariesRequest {
    /// domain_telemetry_log_ids is the list of tenant-level telemetry IDs to query.
    #[prost(string, repeated, tag = "1")]
    pub domain_telemetry_log_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// from is the start of the time range (inclusive). Defaults to 30 days ago if unset.
    #[prost(message, optional, tag = "2")]
    pub from: ::core::option::Option<::prost_types::Timestamp>,
    /// to is the end of the time range (exclusive). Defaults to now if unset.
    #[prost(message, optional, tag = "3")]
    pub to: ::core::option::Option<::prost_types::Timestamp>,
}
/// GetTenantTrafficSummariesResponse contains the aggregated traffic for multiple tenants.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetTenantTrafficSummariesResponse {
    /// summaries is the list of per-tenant traffic summaries.
    #[prost(message, repeated, tag = "1")]
    pub summaries: ::prost::alloc::vec::Vec<TenantTrafficSummary>,
}
/// TenantTrafficSummary is the traffic summary for a single tenant.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TenantTrafficSummary {
    /// domain_telemetry_log_id is the tenant-level telemetry ID.
    #[prost(string, tag = "1")]
    pub domain_telemetry_log_id: ::prost::alloc::string::String,
    /// total_tx_bytes is the total transmitted bytes in the time range.
    #[prost(int64, tag = "2")]
    pub total_tx_bytes: i64,
    /// total_rx_bytes is the total received bytes in the time range.
    #[prost(int64, tag = "3")]
    pub total_rx_bytes: i64,
    /// total_bytes is the sum of tx + rx bytes.
    #[prost(int64, tag = "4")]
    pub total_bytes: i64,
}
// =============================================================================
// Loglyph (client debug logs)
// =============================================================================

/// LoglyphUploadRequest contains a batch of client debug log entries.
/// Used inside StreamLogRequest.loglyph.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LoglyphUploadRequest {
    /// session_id is the ephemeral session identifier.
    #[prost(string, tag = "1")]
    pub session_id: ::prost::alloc::string::String,
    /// client_version is the client version string.
    #[prost(string, tag = "2")]
    pub client_version: ::prost::alloc::string::String,
    /// entries is a list of structured log entries.
    #[prost(message, repeated, tag = "3")]
    pub entries: ::prost::alloc::vec::Vec<LoglyphEntry>,
}
/// LoglyphEntry is a single client debug log entry.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoglyphEntry {
    /// client_time is when the log was generated on the client (RFC3339Nano).
    #[prost(message, optional, tag = "1")]
    pub client_time: ::core::option::Option<::prost_types::Timestamp>,
    /// level is the log level (e.g., "info", "debug", "warn", "error").
    #[prost(string, tag = "2")]
    pub level: ::prost::alloc::string::String,
    /// text is the log message text.
    #[prost(string, tag = "3")]
    pub text: ::prost::alloc::string::String,
    /// payload is optional structured data (JSON-encoded).
    #[prost(string, tag = "4")]
    pub payload: ::prost::alloc::string::String,
    /// proc_id is the process identifier (optional).
    #[prost(uint32, tag = "5")]
    pub proc_id: u32,
    /// proc_seq is the process-level sequence number (optional).
    #[prost(uint64, tag = "6")]
    pub proc_seq: u64,
    /// v is the verbosity level (0 = normal, 1+ = verbose).
    #[prost(int32, tag = "7")]
    pub v: i32,
}
/// LoglyphUploadResponse is returned inside StreamLogResponse.ack
/// when processing loglyph entries. Kept for structured per-type feedback.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoglyphUploadResponse {
    /// accepted is the number of entries successfully stored.
    #[prost(uint32, tag = "1")]
    pub accepted: u32,
    /// dropped is the number of entries dropped.
    #[prost(uint32, tag = "2")]
    pub dropped: u32,
    /// reason is set if any entries were dropped.
    #[prost(string, tag = "3")]
    pub reason: ::prost::alloc::string::String,
}
// =============================================================================
// Orbit (telemetry events)
// =============================================================================

/// OrbitBatchUploadRequest contains a batch of telemetry events from a client.
/// Used inside StreamLogRequest.orbit.
/// The log server identifies the stream via log_stream_id (derived from private-id).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrbitBatchUploadRequest {
    /// version is the client version string (e.g. "1.2.3").
    #[prost(string, tag = "1")]
    pub version: ::prost::alloc::string::String,
    /// session_id is a unique identifier for the client session.
    #[prost(string, tag = "2")]
    pub session_id: ::prost::alloc::string::String,
    /// events is the list of telemetry events to upload.
    #[prost(message, repeated, tag = "3")]
    pub events: ::prost::alloc::vec::Vec<OrbitEvent>,
}
/// OrbitBatchUploadResponse is returned inside StreamLogResponse.ack
/// when processing orbit events. Kept for structured per-type feedback.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OrbitBatchUploadResponse {
    /// accepted is the number of events successfully stored.
    #[prost(uint32, tag = "1")]
    pub accepted: u32,
    /// dropped is the number of events dropped (rate limit, size limit, etc.).
    #[prost(uint32, tag = "2")]
    pub dropped: u32,
    /// reason is set if any events were dropped.
    #[prost(string, tag = "3")]
    pub reason: ::prost::alloc::string::String,
}
/// OrbitEvent is a single telemetry event.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OrbitEvent {
    /// at is the client-side timestamp when the event occurred.
    #[prost(message, optional, tag = "1")]
    pub at: ::core::option::Option<::prost_types::Timestamp>,
    /// peer_hash is the first 8 bytes of SHA256(peer_public_key).
    /// Used for correlation without exposing full keys.
    #[prost(bytes = "vec", tag = "2")]
    pub peer_hash: ::prost::alloc::vec::Vec<u8>,
    /// region_id is the CERF region ID (if applicable).
    #[prost(uint32, tag = "3")]
    pub region_id: u32,
    /// transport is the transport type used.
    #[prost(enumeration = "Transport", tag = "4")]
    pub transport: i32,
    /// payload is one of the event types below.
    #[prost(oneof = "orbit_event::Payload", tags = "10, 11, 12, 13, 14, 15")]
    pub payload: ::core::option::Option<orbit_event::Payload>,
}
/// Nested message and enum types in `OrbitEvent`.
pub mod orbit_event {
    /// payload is one of the event types below.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag = "10")]
        SendResult(super::SendResultEvent),
        #[prost(message, tag = "11")]
        RecvResult(super::RecvResultEvent),
        #[prost(message, tag = "12")]
        CerfConn(super::CerfConnEvent),
        #[prost(message, tag = "13")]
        Ice(super::IceEvent),
        #[prost(message, tag = "14")]
        Filter(super::FilterEvent),
        #[prost(message, tag = "15")]
        PathTransition(super::PathTransitionEvent),
    }
}
/// SendResultEvent records the result of sending a packet.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SendResultEvent {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(string, tag = "2")]
    pub error: ::prost::alloc::string::String,
}
/// RecvResultEvent records the result of receiving a packet.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RecvResultEvent {
    /// kind: 0=data, 1=keepalive, 2=handshake, etc.
    #[prost(int32, tag = "1")]
    pub kind: i32,
    #[prost(uint32, tag = "2")]
    pub size: u32,
}
/// CerfConnEvent records CERF connection state changes.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CerfConnEvent {
    #[prost(enumeration = "cerf_conn_event::State", tag = "1")]
    pub state: i32,
    #[prost(string, tag = "2")]
    pub error: ::prost::alloc::string::String,
}
/// Nested message and enum types in `CerfConnEvent`.
pub mod cerf_conn_event {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum State {
        CerfConnStateUnknown = 0,
        CerfConnStateConnecting = 1,
        CerfConnStateConnected = 2,
        CerfConnStateDisconnected = 3,
        CerfConnStateRecvError = 4,
    }
    impl State {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::CerfConnStateUnknown => "CERF_CONN_STATE_UNKNOWN",
                Self::CerfConnStateConnecting => "CERF_CONN_STATE_CONNECTING",
                Self::CerfConnStateConnected => "CERF_CONN_STATE_CONNECTED",
                Self::CerfConnStateDisconnected => "CERF_CONN_STATE_DISCONNECTED",
                Self::CerfConnStateRecvError => "CERF_CONN_STATE_RECV_ERROR",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "CERF_CONN_STATE_UNKNOWN" => Some(Self::CerfConnStateUnknown),
                "CERF_CONN_STATE_CONNECTING" => Some(Self::CerfConnStateConnecting),
                "CERF_CONN_STATE_CONNECTED" => Some(Self::CerfConnStateConnected),
                "CERF_CONN_STATE_DISCONNECTED" => Some(Self::CerfConnStateDisconnected),
                "CERF_CONN_STATE_RECV_ERROR" => Some(Self::CerfConnStateRecvError),
                _ => None,
            }
        }
    }
}
/// IceEvent records ICE negotiation state changes.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct IceEvent {
    #[prost(enumeration = "ice_event::State", tag = "1")]
    pub state: i32,
    /// e.g. "host", "srflx", "relay"
    #[prost(string, tag = "2")]
    pub candidate_type: ::prost::alloc::string::String,
}
/// Nested message and enum types in `IceEvent`.
pub mod ice_event {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum State {
        IceStateUnknown = 0,
        IceStateChecking = 1,
        IceStateConnected = 2,
        IceStateCompleted = 3,
        IceStateFailed = 4,
        IceStateDisconnected = 5,
        IceStateClosed = 6,
    }
    impl State {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::IceStateUnknown => "ICE_STATE_UNKNOWN",
                Self::IceStateChecking => "ICE_STATE_CHECKING",
                Self::IceStateConnected => "ICE_STATE_CONNECTED",
                Self::IceStateCompleted => "ICE_STATE_COMPLETED",
                Self::IceStateFailed => "ICE_STATE_FAILED",
                Self::IceStateDisconnected => "ICE_STATE_DISCONNECTED",
                Self::IceStateClosed => "ICE_STATE_CLOSED",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "ICE_STATE_UNKNOWN" => Some(Self::IceStateUnknown),
                "ICE_STATE_CHECKING" => Some(Self::IceStateChecking),
                "ICE_STATE_CONNECTED" => Some(Self::IceStateConnected),
                "ICE_STATE_COMPLETED" => Some(Self::IceStateCompleted),
                "ICE_STATE_FAILED" => Some(Self::IceStateFailed),
                "ICE_STATE_DISCONNECTED" => Some(Self::IceStateDisconnected),
                "ICE_STATE_CLOSED" => Some(Self::IceStateClosed),
                _ => None,
            }
        }
    }
}
/// FilterEvent records packet filter decisions.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FilterEvent {
    #[prost(enumeration = "filter_event::Result", tag = "1")]
    pub result: i32,
    /// e.g. "no_matching_rule", "jailed", etc.
    #[prost(string, tag = "2")]
    pub reason: ::prost::alloc::string::String,
}
/// Nested message and enum types in `FilterEvent`.
pub mod filter_event {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum Result {
        FilterResultUnknown = 0,
        FilterResultAccept = 1,
        FilterResultDrop = 2,
    }
    impl Result {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::FilterResultUnknown => "FILTER_RESULT_UNKNOWN",
                Self::FilterResultAccept => "FILTER_RESULT_ACCEPT",
                Self::FilterResultDrop => "FILTER_RESULT_DROP",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "FILTER_RESULT_UNKNOWN" => Some(Self::FilterResultUnknown),
                "FILTER_RESULT_ACCEPT" => Some(Self::FilterResultAccept),
                "FILTER_RESULT_DROP" => Some(Self::FilterResultDrop),
                _ => None,
            }
        }
    }
}
/// PathTransitionEvent records when the active path changes.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PathTransitionEvent {
    #[prost(enumeration = "Transport", tag = "1")]
    pub from: i32,
    #[prost(enumeration = "Transport", tag = "2")]
    pub to: i32,
    /// e.g. "ice_connected", "cerf_fallback", etc.
    #[prost(string, tag = "3")]
    pub reason: ::prost::alloc::string::String,
}
// =============================================================================
// PacketFlowLog (network flow statistics)
// =============================================================================

/// PacketFlowLogUploadRequest contains network flow statistics from a client.
/// Used inside StreamLogRequest.packet_flow.
/// The log server identifies the stream via log_stream_id (derived from private-id).
///
/// Fields 8-11 embed node/tenant identity directly in the payload (A-plan).
/// This makes each log self-contained for SIEM export without requiring
/// server-side JOIN to resolve IPs to node names.
/// These values are sourced from NetworkMapResponse on the client side.
/// Older clients that don't send these fields are backward-compatible
/// (fields default to empty string, log-server stores them as-is).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PacketFlowLogUploadRequest {
    /// logged_at is the timestamp when the stats were collected.
    #[prost(string, tag = "1")]
    pub logged_at: ::prost::alloc::string::String,
    /// started_at is when the measurement period started.
    #[prost(string, tag = "2")]
    pub started_at: ::prost::alloc::string::String,
    /// ended_at is when the measurement period ended.
    #[prost(string, tag = "3")]
    pub ended_at: ::prost::alloc::string::String,
    /// peer_traffic records traffic between Runetale IPs (100.x.y.z <-> 100.x.y.z).
    #[prost(message, repeated, tag = "4")]
    pub peer_traffic: ::prost::alloc::vec::Vec<PacketFlowEntry>,
    /// lan_traffic records traffic on explicitly advertised subnet routes.
    #[prost(message, repeated, tag = "5")]
    pub lan_traffic: ::prost::alloc::vec::Vec<PacketFlowEntry>,
    /// exit_node_traffic records exit node traffic (src is Runetale IP,
    /// protocol/port/dst may be anonymized).
    #[prost(message, repeated, tag = "6")]
    pub exit_node_traffic: ::prost::alloc::vec::Vec<PacketFlowEntry>,
    /// transport_traffic records physical WireGuard layer traffic.
    #[prost(message, repeated, tag = "7")]
    pub transport_traffic: ::prost::alloc::vec::Vec<PacketFlowEntry>,
    /// telemetry_log_id is the per-node UUID assigned by runetale-server
    /// (stored in nodes.telemetry_log_id, delivered via NetworkMapResponse).
    #[prost(string, tag = "8")]
    pub telemetry_log_id: ::prost::alloc::string::String,
    /// domain_telemetry_log_id is the per-tenant UUID assigned by runeauth
    /// (stored in tenant_specs.domain_telemetry_log_id, delivered via NetworkMapResponse).
    #[prost(string, tag = "9")]
    pub domain_telemetry_log_id: ::prost::alloc::string::String,
    /// node_name is the hostname of the reporting node (e.g. "alice-macbook").
    #[prost(string, tag = "10")]
    pub node_name: ::prost::alloc::string::String,
    /// user_email is the email of the user who owns the reporting node.
    #[prost(string, tag = "11")]
    pub user_email: ::prost::alloc::string::String,
    /// One entry per unique destination Runetale IP seen in peer_traffic entries.
    /// Traffic entries reference these by matching PacketFlowEntry.dst IP prefix
    /// against FlowPeerInfo.runetale_ip. This avoids duplicating node info
    /// across multiple traffic entries to the same destination.
    /// Only populated for peer_traffic (Runetale IP <-> Runetale IP).
    /// The client resolves this from NetworkMap.PeerByRunetaleIP(dst_ip).
    #[prost(message, repeated, tag = "12")]
    pub dst_peers: ::prost::alloc::vec::Vec<FlowPeerInfo>,
}
/// FlowPeerInfo describes a peer node involved in traffic.
/// Used in PacketFlowLogUploadRequest.dst_peers:
/// node info appears once per unique destination, and PacketFlowEntry.dst IP
/// references into this list. This keeps payload size ~8% larger instead of ~57%.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FlowPeerInfo {
    /// runetale_ip is the Runetale CGNAT IP (e.g. "100.112.0.7").
    /// Used as the join key with PacketFlowEntry.dst (strip port to match).
    #[prost(string, tag = "1")]
    pub runetale_ip: ::prost::alloc::string::String,
    /// node_name is the hostname (e.g. "db-server.rune54494.rt.net.").
    #[prost(string, tag = "2")]
    pub node_name: ::prost::alloc::string::String,
    /// user_email is the email of the user who owns this node.
    #[prost(string, tag = "3")]
    pub user_email: ::prost::alloc::string::String,
    /// node_id is the telemetry_log_id UUID of the destination node.
    #[prost(string, tag = "4")]
    pub node_id: ::prost::alloc::string::String,
}
/// PacketFlowEntry is a single 5-tuple flow record.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PacketFlowEntry {
    /// proto is the IP protocol number (6=TCP, 17=UDP, 1=ICMPv4, 58=ICMPv6).
    #[prost(uint32, tag = "1")]
    pub proto: u32,
    /// src is the source IP address.
    #[prost(string, tag = "2")]
    pub src: ::prost::alloc::string::String,
    /// dst is the destination IP address.
    #[prost(string, tag = "3")]
    pub dst: ::prost::alloc::string::String,
    /// tx_packets is the number of transmitted packets.
    #[prost(uint64, tag = "4")]
    pub tx_packets: u64,
    /// tx_bytes is the number of transmitted bytes.
    #[prost(uint64, tag = "5")]
    pub tx_bytes: u64,
    /// rx_packets is the number of received packets.
    #[prost(uint64, tag = "6")]
    pub rx_packets: u64,
    /// rx_bytes is the number of received bytes.
    #[prost(uint64, tag = "7")]
    pub rx_bytes: u64,
}
/// PacketFlowLogUploadResponse is returned inside StreamLogResponse.ack
/// when processing flow logs.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PacketFlowLogUploadResponse {
    /// accepted is the number of flow entries successfully stored.
    #[prost(uint32, tag = "1")]
    pub accepted: u32,
}
// =============================================================================
// BiDi Stream messages
// =============================================================================

/// StreamLogRequest is sent by the client on the StreamLogs bidirectional stream.
/// Each message carries exactly one log payload via the oneof field.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StreamLogRequest {
    /// sequence is a client-assigned monotonically increasing number.
    /// The server echoes it back in StreamAck for delivery confirmation.
    #[prost(uint64, tag = "10")]
    pub sequence: u64,
    #[prost(oneof = "stream_log_request::Payload", tags = "1, 2, 3")]
    pub payload: ::core::option::Option<stream_log_request::Payload>,
}
/// Nested message and enum types in `StreamLogRequest`.
pub mod stream_log_request {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        /// packet_flow carries network flow statistics (60s summaries).
        #[prost(message, tag = "1")]
        PacketFlow(super::PacketFlowLogUploadRequest),
        /// orbit carries a batch of telemetry events.
        #[prost(message, tag = "2")]
        Orbit(super::OrbitBatchUploadRequest),
        /// loglyph carries a batch of client debug log entries.
        #[prost(message, tag = "3")]
        Loglyph(super::LoglyphUploadRequest),
    }
}
/// StreamLogResponse is sent by the server on the StreamLogs bidirectional stream.
/// Each message carries either a configuration update or an acknowledgement.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StreamLogResponse {
    #[prost(oneof = "stream_log_response::Directive", tags = "1, 2")]
    pub directive: ::core::option::Option<stream_log_response::Directive>,
}
/// Nested message and enum types in `StreamLogResponse`.
pub mod stream_log_response {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Directive {
        /// config is a server-pushed configuration update.
        /// Sent immediately on connection and whenever tenant config changes.
        #[prost(message, tag = "1")]
        Config(super::LogConfigUpdate),
        /// ack confirms receipt and processing of a client message.
        #[prost(message, tag = "2")]
        Ack(super::StreamAck),
    }
}
/// LogConfigUpdate carries dynamic configuration from the server to the client.
/// Allows the server to adjust client logging behavior without binary updates.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LogConfigUpdate {
    /// poll_period_seconds is the interval between flow log collections.
    /// 0 means use client default (currently 60s).
    #[prost(uint32, tag = "1")]
    pub poll_period_seconds: u32,
    /// min_bytes_threshold is the minimum total bytes for a connection to be logged.
    /// 0 means use client default (currently 256 bytes).
    #[prost(uint64, tag = "2")]
    pub min_bytes_threshold: u64,
    /// netflow_enabled controls whether network flow logs are collected.
    #[prost(bool, tag = "3")]
    pub netflow_enabled: bool,
    /// orbit_enabled controls whether orbit telemetry events are collected.
    #[prost(bool, tag = "4")]
    pub orbit_enabled: bool,
    /// loglyph_enabled controls whether client debug logs are collected.
    #[prost(bool, tag = "5")]
    pub loglyph_enabled: bool,
}
/// StreamAck confirms that the server has received and processed a client message.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StreamAck {
    /// sequence echoes the client's StreamLogRequest.sequence.
    #[prost(uint64, tag = "1")]
    pub sequence: u64,
    /// accepted is the number of entries/events/logs successfully stored.
    #[prost(uint32, tag = "2")]
    pub accepted: u32,
    /// dropped is the number of entries/events/logs dropped (if any).
    #[prost(uint32, tag = "3")]
    pub dropped: u32,
    /// reason is set if any entries were dropped (e.g. "rate_limited", "too_large").
    #[prost(string, tag = "4")]
    pub reason: ::prost::alloc::string::String,
}
/// Transport describes how a packet was sent/received.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Transport {
    Unknown = 0,
    Udp = 1,
    Ice = 2,
    Cerf = 3,
    CerfWs = 4,
}
impl Transport {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "TRANSPORT_UNKNOWN",
            Self::Udp => "TRANSPORT_UDP",
            Self::Ice => "TRANSPORT_ICE",
            Self::Cerf => "TRANSPORT_CERF",
            Self::CerfWs => "TRANSPORT_CERF_WS",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TRANSPORT_UNKNOWN" => Some(Self::Unknown),
            "TRANSPORT_UDP" => Some(Self::Udp),
            "TRANSPORT_ICE" => Some(Self::Ice),
            "TRANSPORT_CERF" => Some(Self::Cerf),
            "TRANSPORT_CERF_WS" => Some(Self::CerfWs),
            _ => None,
        }
    }
}
// @@protoc_insertion_point(module)
