// @generated
// This file is @generated by prost-build.
/// Common type definitions
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Timestamp {
    #[prost(int64, tag = "1")]
    pub seconds: i64,
    #[prost(int32, tag = "2")]
    pub nanos: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LogoutResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OkResponse {
    #[prost(bool, tag = "1")]
    pub ok: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VerifyLoginSessionRequest {
    #[prost(string, tag = "1")]
    pub session_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VerifyLoginSessionResponse {
    #[prost(bool, tag = "1")]
    pub valid: bool,
}
/// User-related message definitions
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UserRole {
    #[prost(string, tag = "1")]
    pub role: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub description: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BaseUserNode {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub ip: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub public_key: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub os: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub version: ::prost::alloc::string::String,
    #[prost(bool, tag = "7")]
    pub is_online: bool,
    #[prost(message, optional, tag = "8")]
    pub last_seen: ::core::option::Option<Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BaseUser {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub email: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub role: ::core::option::Option<UserRole>,
    #[prost(message, repeated, tag = "5")]
    pub nodes: ::prost::alloc::vec::Vec<BaseUserNode>,
    #[prost(message, optional, tag = "6")]
    pub created_at: ::core::option::Option<Timestamp>,
    #[prost(message, optional, tag = "7")]
    pub updated_at: ::core::option::Option<Timestamp>,
}
/// Device-related message definitions
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BaseDevice {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub public_key: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub ip: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub os: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub version: ::prost::alloc::string::String,
    #[prost(bool, tag = "7")]
    pub is_online: bool,
    #[prost(message, optional, tag = "8")]
    pub last_seen: ::core::option::Option<Timestamp>,
    #[prost(message, optional, tag = "9")]
    pub created_at: ::core::option::Option<Timestamp>,
    #[prost(message, optional, tag = "10")]
    pub updated_at: ::core::option::Option<Timestamp>,
}
/// ACL-related message definitions
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Policy {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "4")]
    pub src_nodes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "5")]
    pub dst_nodes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "6")]
    pub ports: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "7")]
    pub protocols: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(bool, tag = "8")]
    pub enabled: bool,
    #[prost(message, optional, tag = "9")]
    pub created_at: ::core::option::Option<Timestamp>,
    #[prost(message, optional, tag = "10")]
    pub updated_at: ::core::option::Option<Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BaseAclNodes {
    #[prost(string, repeated, tag = "1")]
    pub src_nodes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "2")]
    pub dst_nodes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Acl {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub nodes: ::core::option::Option<BaseAclNodes>,
    #[prost(string, repeated, tag = "5")]
    pub ports: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "6")]
    pub protocols: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(bool, tag = "7")]
    pub enabled: bool,
    #[prost(message, optional, tag = "8")]
    pub created_at: ::core::option::Option<Timestamp>,
    #[prost(message, optional, tag = "9")]
    pub updated_at: ::core::option::Option<Timestamp>,
}
/// DNS-related message definitions
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SplitDns {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub domain: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "5")]
    pub nodes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(bool, tag = "6")]
    pub enabled: bool,
    #[prost(message, optional, tag = "7")]
    pub created_at: ::core::option::Option<Timestamp>,
    #[prost(message, optional, tag = "8")]
    pub updated_at: ::core::option::Option<Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Dns {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub domain: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "5")]
    pub nodes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(bool, tag = "6")]
    pub enabled: bool,
    #[prost(message, optional, tag = "7")]
    pub created_at: ::core::option::Option<Timestamp>,
    #[prost(message, optional, tag = "8")]
    pub updated_at: ::core::option::Option<Timestamp>,
}
/// Resource-related message definitions
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BaseResource {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "5")]
    pub labels: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    #[prost(message, optional, tag = "6")]
    pub created_at: ::core::option::Option<Timestamp>,
    #[prost(message, optional, tag = "7")]
    pub updated_at: ::core::option::Option<Timestamp>,
}
/// Fleet-related message definitions
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BaseFleet {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "4")]
    pub nodes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(map = "string, string", tag = "5")]
    pub labels: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    #[prost(message, optional, tag = "6")]
    pub created_at: ::core::option::Option<Timestamp>,
    #[prost(message, optional, tag = "7")]
    pub updated_at: ::core::option::Option<Timestamp>,
}
/// Group-related message definitions
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BaseGroup {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "4")]
    pub nodes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "5")]
    pub users: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "6")]
    pub created_at: ::core::option::Option<Timestamp>,
    #[prost(message, optional, tag = "7")]
    pub updated_at: ::core::option::Option<Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GroupNode {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub ip: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub public_key: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub os: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub version: ::prost::alloc::string::String,
    #[prost(bool, tag = "7")]
    pub is_online: bool,
    #[prost(message, optional, tag = "8")]
    pub last_seen: ::core::option::Option<Timestamp>,
}
/// Linker-related message definitions
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Linker {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub subnet: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "5")]
    pub nodes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(bool, tag = "6")]
    pub enabled: bool,
    #[prost(message, optional, tag = "7")]
    pub created_at: ::core::option::Option<Timestamp>,
    #[prost(message, optional, tag = "8")]
    pub updated_at: ::core::option::Option<Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SubnetLinkerCovertibleNode {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub ip: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub public_key: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub os: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub version: ::prost::alloc::string::String,
    #[prost(bool, tag = "7")]
    pub is_online: bool,
    #[prost(message, optional, tag = "8")]
    pub last_seen: ::core::option::Option<Timestamp>,
}
/// Compose key-related message definitions
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ComposeKey {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub key: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub install_script: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "5")]
    pub created_at: ::core::option::Option<Timestamp>,
    #[prost(message, optional, tag = "6")]
    pub updated_at: ::core::option::Option<Timestamp>,
}
/// Overview-related message definitions
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OverviewResponse {
    #[prost(int32, tag = "1")]
    pub total_nodes: i32,
    #[prost(int32, tag = "2")]
    pub online_nodes: i32,
    #[prost(int32, tag = "3")]
    pub total_users: i32,
    #[prost(int32, tag = "4")]
    pub total_groups: i32,
    #[prost(int32, tag = "5")]
    pub total_acls: i32,
    #[prost(int32, tag = "6")]
    pub total_dns: i32,
    #[prost(int32, tag = "7")]
    pub total_linkers: i32,
    #[prost(int32, tag = "8")]
    pub total_fleets: i32,
    #[prost(int32, tag = "9")]
    pub total_resources: i32,
}
/// DNS-related additional message definitions
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateSplitDnsRequest {
    #[prost(string, tag = "1")]
    pub name_server: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub domain: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateSplitDnsRequest {
    #[prost(message, optional, tag = "1")]
    pub split_dns: ::core::option::Option<SplitDns>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteSplitDnsRequest {
    #[prost(int32, tag = "1")]
    pub split_dns_id: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateDnsSearchDomainsRequest {
    #[prost(string, repeated, tag = "1")]
    pub search_domains: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateDnsNameServersRequest {
    #[prost(string, repeated, tag = "1")]
    pub name_servers: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BaseUpdateDnsRequest {
    #[prost(bool, tag = "1")]
    pub override_local_dns: bool,
}
/// Fleet-related additional message definitions
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateFleetDescriptionRequest {
    #[prost(string, tag = "1")]
    pub description: ::prost::alloc::string::String,
}
/// Compose key-related additional message definitions
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetComposeKeyRequest {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub ports: ::prost::alloc::string::String,
    #[prost(bool, tag = "4")]
    pub is_reusable: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetComposeKeyResponse {
    #[prost(string, tag = "1")]
    pub install_scripts: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub compose_key: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GenerateComposeKeyRequest {
    #[prost(string, tag = "1")]
    pub ports: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
}
/// Team invitation-related message definitions
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InviteTeamMember {
    #[prost(string, tag = "1")]
    pub email: ::prost::alloc::string::String,
    #[prost(enumeration = "UserRoles", tag = "2")]
    pub role: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InviteTeamMembersRequest {
    #[prost(message, repeated, tag = "1")]
    pub members: ::prost::alloc::vec::Vec<InviteTeamMember>,
    #[prost(string, tag = "2")]
    pub redirect_to: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub revalidate_path: ::prost::alloc::string::String,
}
/// Enum definitions
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Os {
    Unspecified = 0,
    Windows = 1,
    Linux = 2,
    Macos = 3,
    Ios = 4,
    Android = 5,
    Unknown = 6,
}
impl Os {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "OS_UNSPECIFIED",
            Self::Windows => "OS_WINDOWS",
            Self::Linux => "OS_LINUX",
            Self::Macos => "OS_MACOS",
            Self::Ios => "OS_IOS",
            Self::Android => "OS_ANDROID",
            Self::Unknown => "OS_UNKNOWN",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "OS_UNSPECIFIED" => Some(Self::Unspecified),
            "OS_WINDOWS" => Some(Self::Windows),
            "OS_LINUX" => Some(Self::Linux),
            "OS_MACOS" => Some(Self::Macos),
            "OS_IOS" => Some(Self::Ios),
            "OS_ANDROID" => Some(Self::Android),
            "OS_UNKNOWN" => Some(Self::Unknown),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Platform {
    Unspecified = 0,
    Docker = 1,
    Cli = 2,
    Linux = 3,
    Gcp = 4,
    Manual = 5,
    Aws = 6,
    Azure = 7,
    Onprem = 8,
    Macos = 9,
    Windows = 10,
    Other = 11,
}
impl Platform {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "PLATFORM_UNSPECIFIED",
            Self::Docker => "PLATFORM_DOCKER",
            Self::Cli => "PLATFORM_CLI",
            Self::Linux => "PLATFORM_LINUX",
            Self::Gcp => "PLATFORM_GCP",
            Self::Manual => "PLATFORM_MANUAL",
            Self::Aws => "PLATFORM_AWS",
            Self::Azure => "PLATFORM_AZURE",
            Self::Onprem => "PLATFORM_ONPREM",
            Self::Macos => "PLATFORM_MACOS",
            Self::Windows => "PLATFORM_WINDOWS",
            Self::Other => "PLATFORM_OTHER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PLATFORM_UNSPECIFIED" => Some(Self::Unspecified),
            "PLATFORM_DOCKER" => Some(Self::Docker),
            "PLATFORM_CLI" => Some(Self::Cli),
            "PLATFORM_LINUX" => Some(Self::Linux),
            "PLATFORM_GCP" => Some(Self::Gcp),
            "PLATFORM_MANUAL" => Some(Self::Manual),
            "PLATFORM_AWS" => Some(Self::Aws),
            "PLATFORM_AZURE" => Some(Self::Azure),
            "PLATFORM_ONPREM" => Some(Self::Onprem),
            "PLATFORM_MACOS" => Some(Self::Macos),
            "PLATFORM_WINDOWS" => Some(Self::Windows),
            "PLATFORM_OTHER" => Some(Self::Other),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum IpProto {
    Unspecified = 0,
    All = 1,
    Tcp = 2,
    Udp = 3,
    Icmpv4 = 4,
    Icmpv6 = 5,
}
impl IpProto {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "IP_PROTO_UNSPECIFIED",
            Self::All => "IP_PROTO_ALL",
            Self::Tcp => "IP_PROTO_TCP",
            Self::Udp => "IP_PROTO_UDP",
            Self::Icmpv4 => "IP_PROTO_ICMPV4",
            Self::Icmpv6 => "IP_PROTO_ICMPV6",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "IP_PROTO_UNSPECIFIED" => Some(Self::Unspecified),
            "IP_PROTO_ALL" => Some(Self::All),
            "IP_PROTO_TCP" => Some(Self::Tcp),
            "IP_PROTO_UDP" => Some(Self::Udp),
            "IP_PROTO_ICMPV4" => Some(Self::Icmpv4),
            "IP_PROTO_ICMPV6" => Some(Self::Icmpv6),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ExpiryTime {
    Unspecified = 0,
    OneMonth = 1,
    TwoMonth = 2,
    ThreeMonth = 3,
}
impl ExpiryTime {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "EXPIRY_TIME_UNSPECIFIED",
            Self::OneMonth => "EXPIRY_TIME_ONE_MONTH",
            Self::TwoMonth => "EXPIRY_TIME_TWO_MONTH",
            Self::ThreeMonth => "EXPIRY_TIME_THREE_MONTH",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "EXPIRY_TIME_UNSPECIFIED" => Some(Self::Unspecified),
            "EXPIRY_TIME_ONE_MONTH" => Some(Self::OneMonth),
            "EXPIRY_TIME_TWO_MONTH" => Some(Self::TwoMonth),
            "EXPIRY_TIME_THREE_MONTH" => Some(Self::ThreeMonth),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum UserRoles {
    UserRoleUnspecified = 0,
    UserRoleAdmin = 1,
    UserRoleUser = 2,
}
impl UserRoles {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::UserRoleUnspecified => "USER_ROLE_UNSPECIFIED",
            Self::UserRoleAdmin => "USER_ROLE_ADMIN",
            Self::UserRoleUser => "USER_ROLE_USER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "USER_ROLE_UNSPECIFIED" => Some(Self::UserRoleUnspecified),
            "USER_ROLE_ADMIN" => Some(Self::UserRoleAdmin),
            "USER_ROLE_USER" => Some(Self::UserRoleUser),
            _ => None,
        }
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Endpoint {
    /// net.UDPAddrを文字列で表現 (e.g., "192.168.1.1:51820")
    #[prost(string, tag = "1")]
    pub addr: ::prost::alloc::string::String,
    /// "turn" or "stun" from ice_endpoint.go
    #[prost(string, tag = "2")]
    pub r#type: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HashiStatus {
    #[prost(string, tag = "1")]
    pub backend_state: ::prost::alloc::string::String,
    /// netip.Addr を文字列として扱う
    #[prost(string, repeated, tag = "2")]
    pub runetale_ips: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "3")]
    pub interactive_login_url: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub self_: ::core::option::Option<PeerStatus>,
    /// map\[key.NodePublic\]*PeerStatus
    #[prost(map = "string, message", tag = "5")]
    pub peer: ::std::collections::HashMap<::prost::alloc::string::String, PeerStatus>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PeerStatus {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(string, tag = "2")]
    pub public_key: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub os: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub host_name: ::prost::alloc::string::String,
    /// netip.Addr を文字列として扱う
    #[prost(string, repeated, tag = "5")]
    pub runetale_ips: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "6")]
    pub peer_api_url: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// \[netip.Prefix\] を文字列のリストで表現
    #[prost(string, repeated, tag = "7")]
    pub allowed_ips: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(int64, tag = "8")]
    pub rx_bytes: i64,
    #[prost(int64, tag = "9")]
    pub tx_bytes: i64,
    #[prost(message, optional, tag = "10")]
    pub last_handshake: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "11")]
    pub last_write: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, repeated, tag = "12")]
    pub addrs: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "13")]
    pub cur_addr: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "14")]
    pub ice_addr: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "15")]
    pub advertise_routes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// subnet linkerを許可するかどうか
    #[prost(bool, tag = "16")]
    pub is_snat_subnet: bool,
    /// active: 最後のパケット送信から45秒以内か（wonderwallで設定）
    #[prost(bool, tag = "17")]
    pub active: bool,
    /// online: サーバーに接続しているか (wonderwallで設定)
    #[prost(bool, tag = "18")]
    pub online: bool,
    /// last_seen: 最後にオンラインだった時刻（オフライン時のみ設定）
    #[prost(message, optional, tag = "19")]
    pub last_seen: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UserspacePeerEngineStatus {
    #[prost(message, optional, tag = "1")]
    pub got_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, repeated, tag = "2")]
    pub peers: ::prost::alloc::vec::Vec<CompactPeerStatus>,
    /// \[\]*runecfg.Endpoint
    #[prost(message, repeated, tag = "3")]
    pub local_addrs: ::prost::alloc::vec::Vec<Endpoint>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CompactPeerStatus {
    #[prost(string, tag = "1")]
    pub node_key: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub tx_bytes: i64,
    #[prost(int64, tag = "3")]
    pub rx_bytes: i64,
    #[prost(message, optional, tag = "4")]
    pub last_handshake: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PingResult {
    #[prost(string, tag = "1")]
    pub ip: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub node_ip: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub node_name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub err: ::prost::alloc::string::String,
    #[prost(double, tag = "5")]
    pub latency_seconds: f64,
    #[prost(string, tag = "6")]
    pub endpoint: ::prost::alloc::string::String,
    #[prost(uint32, tag = "7")]
    pub peer_api_port: u32,
    #[prost(string, tag = "8")]
    pub peer_api_url: ::prost::alloc::string::String,
    #[prost(bool, tag = "9")]
    pub is_local_ip: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ComposeRequest {
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PingRequest {
    #[prost(string, tag = "1")]
    pub ip: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(int32, tag = "3")]
    pub size: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StopRequest {
    #[prost(string, tag = "1")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NetCheckReport {
    #[prost(message, optional, tag = "1")]
    pub now: ::core::option::Option<::prost_types::Timestamp>,
    /// a UDP STUN round trip completed
    #[prost(bool, tag = "2")]
    pub udp: bool,
    /// an IPv6 STUN round trip completed
    #[prost(bool, tag = "3")]
    pub ipv6: bool,
    /// an IPv4 STUN round trip completed
    #[prost(bool, tag = "4")]
    pub ipv4: bool,
    /// an IPv6 packet was able to be sent
    #[prost(bool, tag = "5")]
    pub ipv6_can_send: bool,
    /// an IPv4 packet was able to be sent
    #[prost(bool, tag = "6")]
    pub ipv4_can_send: bool,
    /// could bind a socket to ::1
    #[prost(bool, tag = "7")]
    pub os_has_ipv6: bool,
    /// best IPv4 global address (netip.AddrPort as string)
    #[prost(string, tag = "8")]
    pub global_v4: ::prost::alloc::string::String,
    /// best IPv6 global address (netip.AddrPort as string)
    #[prost(string, tag = "9")]
    pub global_v6: ::prost::alloc::string::String,
    /// STUN server URI -> latency in milliseconds
    #[prost(map = "string, int64", tag = "10")]
    pub stun_latency: ::std::collections::HashMap<::prost::alloc::string::String, i64>,
    /// TURN server URI -> latency in milliseconds
    #[prost(map = "string, int64", tag = "11")]
    pub turn_latency: ::std::collections::HashMap<::prost::alloc::string::String, i64>,
    /// errors encountered during the check
    #[prost(string, repeated, tag = "12")]
    pub errors: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// CERF relay latency per region. Key is "regionCode" (e.g. "tokyo"), value is latency in milliseconds.
    #[prost(map = "string, int64", tag = "13")]
    pub cerf_latency: ::std::collections::HashMap<::prost::alloc::string::String, i64>,
    /// preferred_cerf_region is the region code of the nearest (lowest latency) CERF relay.
    #[prost(string, tag = "14")]
    pub preferred_cerf_region: ::prost::alloc::string::String,
    /// preferred_cerf_region_id is the region ID of the nearest CERF relay.
    #[prost(uint32, tag = "15")]
    pub preferred_cerf_region_id: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoginNodeResponse {
    #[prost(bool, tag = "1")]
    pub is_registered: bool,
    #[prost(string, tag = "2")]
    pub login_url: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "3")]
    pub ip: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "4")]
    pub cidr: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub signal_host: ::prost::alloc::string::String,
    #[prost(uint64, tag = "6")]
    pub signal_port: u64,
    #[prost(uint64, tag = "7")]
    pub user_id: u64,
    #[prost(string, tag = "8")]
    pub email: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub display_name: ::prost::alloc::string::String,
    #[prost(string, tag = "10")]
    pub login_name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoginSessionResponse {
    /// host ip
    #[prost(string, repeated, tag = "1")]
    pub ip: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// host wireguard cidr
    #[prost(string, tag = "2")]
    pub cidr: ::prost::alloc::string::String,
    /// host name
    #[prost(string, tag = "3")]
    pub host: ::prost::alloc::string::String,
    /// host os
    #[prost(string, tag = "4")]
    pub os: ::prost::alloc::string::String,
    /// host computer name
    #[prost(string, tag = "5")]
    pub computer_name: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub signal_server_host: ::prost::alloc::string::String,
    #[prost(uint64, tag = "7")]
    pub signal_server_port: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetInvitationRequest {
    #[prost(string, tag = "1")]
    pub invite_code: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetInvitationResponse {
    #[prost(string, tag = "1")]
    pub email: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub invite_code: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NegotiationMessage {
    #[prost(enumeration = "NegotiationType", tag = "1")]
    pub r#type: i32,
    /// remote node key of the Peer you want to connect to
    #[prost(string, tag = "2")]
    pub dst_node_key: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub dst_wg_pub_key: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub u_flag: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub pwd: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub candidate: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "7")]
    pub session_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "8")]
    pub flea_packet_message: ::core::option::Option<FleaPacketMessage>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FleaPacketMessage {
    /// remote node key of the Peer you want to connect to
    #[prost(string, tag = "1")]
    pub dst_node_key: ::prost::alloc::string::String,
    /// node key of the originating peer to be sent to the remote peer
    #[prost(string, tag = "2")]
    pub src_node_key: ::prost::alloc::string::String,
    /// wgPubKey from request node
    #[prost(string, tag = "3")]
    pub wg_pub_key: ::prost::alloc::string::String,
    /// "ip:port" 形式を最大8件
    #[prost(string, repeated, tag = "4")]
    pub endpoints: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// 鮮度/デバッグ用
    #[prost(uint64, optional, tag = "5")]
    pub epoch_ts: ::core::option::Option<u64>,
    /// 重褊定
    #[prost(bytes = "vec", optional, tag = "6")]
    pub dedupe_id: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HandshakeRequest {
    /// remote node key of the Peer you want to connect to
    #[prost(string, tag = "1")]
    pub dst_node_key: ::prost::alloc::string::String,
    /// node key of the originating peer to be sent to the remote peer
    #[prost(string, tag = "2")]
    pub src_node_key: ::prost::alloc::string::String,
    /// wgPubKey from request node
    #[prost(string, tag = "3")]
    pub wg_pub_key: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub u_flag: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub pwd: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "6")]
    pub session_id: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CandidateRequest {
    /// remote node key of the Peer you want to connect to
    #[prost(string, tag = "1")]
    pub dst_node_key: ::prost::alloc::string::String,
    /// node key of the originating peer to be sent to the remote peer
    #[prost(string, tag = "2")]
    pub src_node_key: ::prost::alloc::string::String,
    /// wgPubKey from request node
    #[prost(string, tag = "3")]
    pub wg_pub_key: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub candidate: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum NegotiationType {
    Offer = 0,
    Answer = 1,
    Candidate = 2,
    Sayhello = 3,
}
impl NegotiationType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Offer => "OFFER",
            Self::Answer => "ANSWER",
            Self::Candidate => "CANDIDATE",
            Self::Sayhello => "SAYHELLO",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "OFFER" => Some(Self::Offer),
            "ANSWER" => Some(Self::Answer),
            "CANDIDATE" => Some(Self::Candidate),
            "SAYHELLO" => Some(Self::Sayhello),
            _ => None,
        }
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Node {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub node_id: u64,
    #[prost(string, tag = "3")]
    pub node_key: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub wg_pub_key: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "5")]
    pub allowed_i_ps: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// e.g. 100.x.y.z/16, fe80::/64
    #[prost(string, repeated, tag = "6")]
    pub addresses: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(uint64, tag = "7")]
    pub user_id: u64,
    #[prost(string, tag = "8")]
    pub email: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub display_name: ::prost::alloc::string::String,
    #[prost(string, tag = "10")]
    pub login_name: ::prost::alloc::string::String,
    #[prost(string, tag = "11")]
    pub host_os: ::prost::alloc::string::String,
    #[prost(string, tag = "12")]
    pub rune_key: ::prost::alloc::string::String,
    /// cerfHomeRegionId is this node's home CERF region ID.
    /// The server must always set this (defaulting to NetworkMapResponse.defaultCerfRegionId).
    #[prost(uint32, tag = "13")]
    pub cerf_home_region_id: u32,
    /// online indicates whether the node is connected to the server
    #[prost(bool, tag = "14")]
    pub online: bool,
    /// lastSeen is when the node was last online (only set when offline)
    #[prost(message, optional, tag = "15")]
    pub last_seen: ::core::option::Option<::prost_types::Timestamp>,
    /// keyExpiry is when this node's key expires. Zero value means no expiry.
    /// After this time, the node must re-authenticate to continue using the network.
    #[prost(message, optional, tag = "16")]
    pub key_expiry: ::core::option::Option<::prost_types::Timestamp>,
    /// expired indicates whether the server has marked this node's key as expired.
    /// When true, the node should initiate key rotation or re-authentication.
    #[prost(bool, tag = "17")]
    pub expired: bool,
    /// keySignature is the CBOR-encoded NodeKeySignature for Network Lock (TKA).
    /// Only set when Network Lock is enabled for the Runetale Network.
    #[prost(bytes = "vec", tag = "18")]
    pub key_signature: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ComposeNodeResponse {
    #[prost(string, tag = "1")]
    pub ip: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub cidr: ::prost::alloc::string::String,
    #[prost(uint64, tag = "3")]
    pub user_id: u64,
    #[prost(string, tag = "4")]
    pub email: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub display_name: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub login_name: ::prost::alloc::string::String,
}
/// NetworkMapRequest is sent from client to server in the ConnectNetworkMapTable stream.
/// It contains the client's VPN state and is used for keepalive.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NetworkMapRequest {
    /// vpn_running indicates whether the VPN is currently active (up=true, down=false).
    /// This is different from the stream connection status - the stream stays connected
    /// even when VPN is down, allowing for faster reconnection.
    #[prost(bool, optional, tag = "1")]
    pub vpn_running: ::core::option::Option<bool>,
    /// is_keepalive indicates if this is a periodic keepalive message.
    /// When false, it's a state change notification.
    #[prost(bool, optional, tag = "2")]
    pub is_keepalive: ::core::option::Option<bool>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NetPortRange {
    /// 以下のような形式
    /// - IPv4 or IPv6の単一のIPアドレス
    /// - "*" は全て許可
    /// - "192.168.0.0/16" cidrが含まれたipの範囲
    #[prost(string, tag = "1")]
    pub ip: ::prost::alloc::string::String,
    /// portのフォーマットは
    /// - 全て指定の `*` か
    /// - 単一指定の `22` か
    /// - 複数指定の `80, 443` か `2つまで`
    /// - 範囲指定の `100-200``
    /// - 単一のportの場合はlastにも同じポート番号が入る
    #[prost(message, optional, tag = "2")]
    pub ports: ::core::option::Option<net_port_range::PortRange>,
    /// advertiseすることが許可されたIP範囲
    /// 1.2.3.4/16のIP+Maskの形
    /// "10.0.0.0/8,192.172.0.0/24"のようにcommaで区切る
    #[prost(string, tag = "3")]
    pub advertised_routes: ::prost::alloc::string::String,
}
/// Nested message and enum types in `NetPortRange`.
pub mod net_port_range {
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct PortRange {
        #[prost(uint64, tag = "1")]
        pub first: u64,
        #[prost(uint64, tag = "2")]
        pub last: u64,
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FilterRule {
    /// source ips, 
    /// - "192.168.0.0/16" cidrが含まれたipの範囲
    #[prost(string, repeated, tag = "1")]
    pub src_ips: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// dstのpeerのリスト
    #[prost(message, repeated, tag = "2")]
    pub dsts: ::prost::alloc::vec::Vec<NetPortRange>,
    /// <https://www.iana.org/assignments/protocol-numbers/protocol-numbers.xhtml>
    /// protocol numbers
    /// Unknown = 0x00
    /// ICMPv4  = 0x01
    /// ICMPv6  = 0x3a
    /// TCP     = 0x06
    /// UDP     = 0x11
    #[prost(uint32, repeated, tag = "3")]
    pub i_p_proto: ::prost::alloc::vec::Vec<u32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NetworkMapResponse {
    /// このmapのsequential id
    #[prost(uint64, tag = "1")]
    pub seq: u64,
    /// このNodeの情報
    #[prost(message, optional, tag = "2")]
    pub node: ::core::option::Option<Node>,
    /// このNodeがアクセスするpeers, つまりremote nodesの情報が含まれている
    #[prost(message, repeated, tag = "3")]
    pub peers: ::prost::alloc::vec::Vec<Node>,
    /// 変更があった場合のPeers
    /// serverで差分更新される
    #[prost(message, repeated, tag = "4")]
    pub peers_changed: ::prost::alloc::vec::Vec<Node>,
    /// 消された場合のPeersのNodeID
    #[prost(uint64, repeated, tag = "5")]
    pub peers_removed: ::prost::alloc::vec::Vec<u64>,
    /// Firewall Rules
    #[prost(message, repeated, tag = "6")]
    pub packet_filter: ::prost::alloc::vec::Vec<FilterRule>,
    /// このnodeがadvertiseするIPアドレス
    /// 1.2.3.4/16のIP+Maskの形
    /// "10.0.0.0/8,192.172.0.0/24"のようにcommaで区切る
    #[prost(string, tag = "7")]
    pub advertised_route: ::prost::alloc::string::String,
    /// jailedがtrueの場合全てのパケットを拒否する
    #[prost(bool, tag = "8")]
    pub jailed: bool,
    #[prost(message, repeated, tag = "9")]
    pub ice_table: ::prost::alloc::vec::Vec<Node>,
    #[prost(message, optional, tag = "10")]
    pub dns: ::core::option::Option<DnsConfig>,
    #[prost(message, repeated, tag = "11")]
    pub app_linker: ::prost::alloc::vec::Vec<AppLinker>,
    /// cerfMap describes available CERF relay nodes.
    #[prost(message, optional, tag = "20")]
    pub cerf_map: ::core::option::Option<CerfMap>,
    /// defaultCerfRegionId is the default region to use when a peer's Node.cerfHomeRegionId is unset.
    #[prost(uint32, tag = "21")]
    pub default_cerf_region_id: u32,
    /// telemetry_log_id is a server-generated ID for Orbit telemetry logging (per-node).
    /// If empty, the client should not collect or upload Orbit telemetry.
    /// This is used to control telemetry collection based on the user's plan.
    #[prost(string, tag = "22")]
    pub telemetry_log_id: ::prost::alloc::string::String,
    /// domain_telemetry_log_id is a server-generated ID for NetworkFlowLogs (per-tenant).
    /// If empty, the client should not collect or upload NetworkFlowLogs.
    /// All nodes in the same tenant share this ID for unified log streaming.
    #[prost(string, tag = "23")]
    pub domain_telemetry_log_id: ::prost::alloc::string::String,
    /// capabilities is a list of server-granted capabilities that control feature availability.
    /// Examples: "runetale:telemetry", "runetale:network-logs", "runetale:log-exit-flows"
    /// The client checks these capabilities to enable/disable features.
    #[prost(string, repeated, tag = "24")]
    pub capabilities: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// server_time is the current timestamp according to the server.
    /// The client uses this to detect clock skew between local and server time,
    /// which is critical for accurate key expiry evaluation.
    #[prost(message, optional, tag = "25")]
    pub server_time: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CerfMap {
    #[prost(message, repeated, tag = "1")]
    pub regions: ::prost::alloc::vec::Vec<CerfRegion>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CerfRegion {
    #[prost(uint32, tag = "1")]
    pub region_id: u32,
    /// e.g. "tokyo"
    #[prost(string, tag = "2")]
    pub region_code: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub nodes: ::prost::alloc::vec::Vec<CerfNode>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CerfNode {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// e.g. cerftokyo.runetale.com
    #[prost(string, tag = "2")]
    pub host_name: ::prost::alloc::string::String,
    /// typically 443
    #[prost(uint32, tag = "3")]
    pub cerf_port: u32,
    /// typically 3478
    #[prost(uint32, tag = "4")]
    pub stun_port: u32,
    /// prefer websocket transport when available
    #[prost(bool, tag = "5")]
    pub websocket_only: bool,
    /// dev/test override
    #[prost(bool, tag = "6")]
    pub force_http: bool,
    /// STUN-only node (no /cerf relay)
    #[prost(bool, tag = "7")]
    pub stun_only: bool,
    /// optional: direct IPv4 address to bypass DNS resolution
    #[prost(string, tag = "8")]
    pub ipv4: ::prost::alloc::string::String,
    /// optional: direct IPv6 address to bypass DNS resolution
    #[prost(string, tag = "9")]
    pub ipv6: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AppLinker {
    /// NameはこのAppLinkerの名前です。
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// Domainsは指定されたAppLinkerによってサービスされるドメインの一覧です。
    /// ドメインは以下の形式を取ることができます
    /// - example.com
    /// - *.example.com
    #[prost(string, repeated, tag = "2")]
    pub domains: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Routesは指定されたAppLinkerrによってアドバタイズされる事前定義されたルートの一覧です。
    /// ルートはCIDR表記で表現されます（例：192.168.1.0/24）。
    #[prost(string, repeated, tag = "3")]
    pub routes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Resolver {
    #[prost(string, tag = "1")]
    pub addr: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Resolvers {
    #[prost(message, repeated, tag = "1")]
    pub resolvers: ::prost::alloc::vec::Vec<Resolver>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DnsConfig {
    /// Resolversは使用するDNSリゾルバの一覧、優先順位順。
    /// デフォルトでは設定されていない。
    /// 有効にすると接続されたクライアントはローカルのDNS設定を無視し、
    /// 常にこれらのグローバルネームサーバーを使用する。
    /// 設定される場合は以下のような値が入る
    /// - 8.8.8.8
    /// - 9.9.9.9
    /// - 2001:4860:4860::8888
    /// - 2001:4860:4860::9999
    #[prost(message, repeated, tag = "1")]
    pub resolvers: ::prost::alloc::vec::Vec<Resolver>,
    /// RoutesはDNS名のサフィックス（接尾辞）を、DNSリゾルバのセットにマッピングします。
    /// 値が空のスライスである場合、そのサフィックスはWonderDNSの100.200.100.200で処理される。
    /// マップのキーはFQDNのsuffix
    /// 例えば"printer.office.example.com."の場合は
    /// "office.example.com."になる。
    /// e.g. office.example.com.:\["178.10.3.1"\]
    /// - 2025/3/27時点では主にSplit DNSで使用する。
    #[prost(map = "string, message", tag = "2")]
    pub routes: ::std::collections::HashMap<::prost::alloc::string::String, Resolvers>,
    /// SearchDomainsはたとえばあるRunetに"example.com"と"test.com"が検索ドメインとして設定されている場合、
    /// ユーザーがserverという名前を入力すると、Runetaleは
    /// 	1. server.example.comを設定されたネームサーバー（例：8.8.8.8 や 1.1.1.1）で検索します。
    /// 	2. 一致しなければ、次にserver.test.comを同様のネームサーバーで検索します。
    /// e.g. \["example.com","test.com"\] のような感じ
    #[prost(string, repeated, tag = "3")]
    pub search_domains: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// 出口ノードとして DNS プロキシを行う際に
    /// 応答を無視するDNSサフィックスのリスト
    /// defaultでは\[.rt.net\]
    #[prost(string, repeated, tag = "4")]
    pub exit_node_filterd: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// wonderdnsを有効にするかどうか
    #[prost(bool, tag = "5")]
    pub enabled_wonder_dns: bool,
}
/// RotateWgKeyRequest is sent when a node wants to rotate its WireGuard key.
/// NodeKey is not rotated; the server identifies the node via gRPC metadata.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RotateWgKeyRequest {
    /// oldWgPubKey is the current WireGuard public key (for verification)
    #[prost(string, tag = "3")]
    pub old_wg_pub_key: ::prost::alloc::string::String,
    /// newWgPubKey is the new WireGuard public key to rotate to
    #[prost(string, tag = "4")]
    pub new_wg_pub_key: ::prost::alloc::string::String,
    /// nodeKeySignature is the new NodeKeySignature if Network Lock is enabled.
    /// This must be signed by the node's rotation key or a trusted NL key.
    #[prost(bytes = "vec", tag = "7")]
    pub node_key_signature: ::prost::alloc::vec::Vec<u8>,
}
/// RotateWgKeyResponse is returned after a successful WireGuard key rotation.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RotateWgKeyResponse {
    /// success indicates whether the key rotation was successful
    #[prost(bool, tag = "1")]
    pub success: bool,
    /// newKeyExpiry is the new expiry time for the rotated key
    #[prost(message, optional, tag = "2")]
    pub new_key_expiry: ::core::option::Option<::prost_types::Timestamp>,
    /// error is set if success is false
    #[prost(string, tag = "3")]
    pub error: ::prost::alloc::string::String,
}
/// NetworkLockInitRequest initializes Network Lock for the Runetale Network.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NetworkLockInitRequest {
    /// keys are the initial trusted signing keys (NL public keys)
    #[prost(message, repeated, tag = "1")]
    pub keys: ::prost::alloc::vec::Vec<NetworkLockKey>,
    /// disablementSecret is a secret that can be used to disable Network Lock
    #[prost(bytes = "vec", tag = "2")]
    pub disablement_secret: ::prost::alloc::vec::Vec<u8>,
}
/// NetworkLockInitResponse is returned after Network Lock initialization.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NetworkLockInitResponse {
    /// success indicates whether initialization was successful
    #[prost(bool, tag = "1")]
    pub success: bool,
    /// error is set if success is false
    #[prost(string, tag = "2")]
    pub error: ::prost::alloc::string::String,
}
/// NetworkLockSignRequest requests signing of a node key.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NetworkLockSignRequest {
    /// nodeKey is the public node key to sign
    #[prost(string, tag = "1")]
    pub node_key: ::prost::alloc::string::String,
    /// rotationPublic is an optional ed25519 public key for future key rotations.
    /// If set, the node can rotate its key by signing with this rotation key.
    #[prost(bytes = "vec", tag = "2")]
    pub rotation_public: ::prost::alloc::vec::Vec<u8>,
}
/// NetworkLockSignResponse returns the signed node key signature.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NetworkLockSignResponse {
    /// signature is the CBOR-encoded NodeKeySignature
    #[prost(bytes = "vec", tag = "1")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    /// error is set if signing failed
    #[prost(string, tag = "2")]
    pub error: ::prost::alloc::string::String,
}
/// NetworkLockDisableRequest disables Network Lock for the Runetale Network.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NetworkLockDisableRequest {
    /// disablementSecret is the secret provided during initialization
    #[prost(bytes = "vec", tag = "1")]
    pub disablement_secret: ::prost::alloc::vec::Vec<u8>,
}
/// NetworkLockDisableResponse is returned after disabling Network Lock.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NetworkLockDisableResponse {
    /// success indicates whether disabling was successful
    #[prost(bool, tag = "1")]
    pub success: bool,
    /// error is set if success is false
    #[prost(string, tag = "2")]
    pub error: ::prost::alloc::string::String,
}
/// NetworkLockStatusResponse returns the current Network Lock status.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NetworkLockStatusResponse {
    /// enabled indicates whether Network Lock is enabled
    #[prost(bool, tag = "1")]
    pub enabled: bool,
    /// head is the current AUM chain head hash (32 bytes)
    #[prost(bytes = "vec", tag = "2")]
    pub head: ::prost::alloc::vec::Vec<u8>,
    /// publicKey is this node's Network Lock public key
    #[prost(bytes = "vec", tag = "3")]
    pub public_key: ::prost::alloc::vec::Vec<u8>,
    /// nodeKey is this node's current node public key
    #[prost(string, tag = "4")]
    pub node_key: ::prost::alloc::string::String,
    /// nodeKeySigned indicates whether this node's key is properly signed
    #[prost(bool, tag = "5")]
    pub node_key_signed: bool,
    /// trustedKeys are the currently trusted signing keys
    #[prost(message, repeated, tag = "6")]
    pub trusted_keys: ::prost::alloc::vec::Vec<NetworkLockKey>,
    /// filteredPeers are peers that failed Network Lock verification
    #[prost(message, repeated, tag = "7")]
    pub filtered_peers: ::prost::alloc::vec::Vec<FilteredPeer>,
}
/// NetworkLockKey represents a trusted Network Lock signing key.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NetworkLockKey {
    /// keyId is the key identifier (hash of the public key)
    #[prost(bytes = "vec", tag = "1")]
    pub key_id: ::prost::alloc::vec::Vec<u8>,
    /// publicKey is the ed25519 public key
    #[prost(bytes = "vec", tag = "2")]
    pub public_key: ::prost::alloc::vec::Vec<u8>,
    /// kind is the key type (e.g., "nl" for Network Lock key)
    #[prost(string, tag = "3")]
    pub kind: ::prost::alloc::string::String,
    /// votes is the voting weight of this key (for threshold signing)
    #[prost(uint32, tag = "4")]
    pub votes: u32,
    /// comment is an optional human-readable description
    #[prost(string, tag = "5")]
    pub comment: ::prost::alloc::string::String,
}
/// FilteredPeer represents a peer that was filtered due to Network Lock.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FilteredPeer {
    /// nodeId is the peer's node ID
    #[prost(uint64, tag = "1")]
    pub node_id: u64,
    /// name is the peer's hostname
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// nodeKey is the peer's node public key
    #[prost(string, tag = "3")]
    pub node_key: ::prost::alloc::string::String,
    /// reason is why the peer was filtered
    #[prost(string, tag = "4")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoginResponse {
    #[prost(string, tag = "1")]
    pub sub: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub tenant_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub domain: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub provider_id: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub email: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub picture: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoginRequest {
    #[prost(string, tag = "1")]
    pub sub: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub tenant_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub domain: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub provider_id: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub email: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub picture: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub invite_code: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AuthenticateResponse {
    #[prost(string, tag = "1")]
    pub domain: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub email: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub sub: ::prost::alloc::string::String,
    #[prost(bool, tag = "5")]
    pub is_registered: bool,
    #[prost(bool, tag = "6")]
    pub is_invited: bool,
}
/// OrbitBatchRequest contains a batch of telemetry events from a client.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrbitBatchRequest {
    /// version is the client version string (e.g. "1.2.3").
    #[prost(string, tag = "1")]
    pub version: ::prost::alloc::string::String,
    /// session_id is a unique identifier for the client session.
    #[prost(string, tag = "2")]
    pub session_id: ::prost::alloc::string::String,
    /// node_id is the node ID (optional, for backward compatibility).
    #[prost(uint64, tag = "3")]
    pub node_id: u64,
    /// events is the list of telemetry events to upload.
    #[prost(message, repeated, tag = "4")]
    pub events: ::prost::alloc::vec::Vec<OrbitEvent>,
}
/// OrbitBatchResponse is returned after processing a batch.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OrbitBatchResponse {
    /// accepted is the number of events successfully stored.
    #[prost(uint32, tag = "1")]
    pub accepted: u32,
    /// dropped is the number of events dropped (rate limit, size limit, etc.).
    #[prost(uint32, tag = "2")]
    pub dropped: u32,
    /// reason is set if any events were dropped.
    #[prost(string, tag = "3")]
    pub reason: ::prost::alloc::string::String,
}
/// OrbitEvent is a single telemetry event.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OrbitEvent {
    /// at is the client-side timestamp when the event occurred.
    #[prost(message, optional, tag = "1")]
    pub at: ::core::option::Option<::prost_types::Timestamp>,
    /// peer_hash is the first 8 bytes of SHA256(peer_public_key).
    /// Used for correlation without exposing full keys.
    #[prost(bytes = "vec", tag = "2")]
    pub peer_hash: ::prost::alloc::vec::Vec<u8>,
    /// region_id is the CERF region ID (if applicable).
    #[prost(uint32, tag = "3")]
    pub region_id: u32,
    /// transport is the transport type used.
    #[prost(enumeration = "Transport", tag = "4")]
    pub transport: i32,
    /// payload is one of the event types below.
    #[prost(oneof = "orbit_event::Payload", tags = "10, 11, 12, 13, 14, 15")]
    pub payload: ::core::option::Option<orbit_event::Payload>,
}
/// Nested message and enum types in `OrbitEvent`.
pub mod orbit_event {
    /// payload is one of the event types below.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag = "10")]
        SendResult(super::SendResultEvent),
        #[prost(message, tag = "11")]
        RecvResult(super::RecvResultEvent),
        #[prost(message, tag = "12")]
        CerfConn(super::CerfConnEvent),
        #[prost(message, tag = "13")]
        Ice(super::IceEvent),
        #[prost(message, tag = "14")]
        Filter(super::FilterEvent),
        #[prost(message, tag = "15")]
        PathTransition(super::PathTransitionEvent),
    }
}
/// SendResultEvent records the result of sending a packet.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SendResultEvent {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(string, tag = "2")]
    pub error: ::prost::alloc::string::String,
}
/// RecvResultEvent records the result of receiving a packet.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RecvResultEvent {
    /// kind: 0=data, 1=keepalive, 2=handshake, etc.
    #[prost(int32, tag = "1")]
    pub kind: i32,
    #[prost(uint32, tag = "2")]
    pub size: u32,
}
/// CerfConnEvent records CERF connection state changes.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CerfConnEvent {
    #[prost(enumeration = "cerf_conn_event::State", tag = "1")]
    pub state: i32,
    #[prost(string, tag = "2")]
    pub error: ::prost::alloc::string::String,
}
/// Nested message and enum types in `CerfConnEvent`.
pub mod cerf_conn_event {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum State {
        CerfConnStateUnknown = 0,
        CerfConnStateConnecting = 1,
        CerfConnStateConnected = 2,
        CerfConnStateDisconnected = 3,
        CerfConnStateRecvError = 4,
    }
    impl State {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::CerfConnStateUnknown => "CERF_CONN_STATE_UNKNOWN",
                Self::CerfConnStateConnecting => "CERF_CONN_STATE_CONNECTING",
                Self::CerfConnStateConnected => "CERF_CONN_STATE_CONNECTED",
                Self::CerfConnStateDisconnected => "CERF_CONN_STATE_DISCONNECTED",
                Self::CerfConnStateRecvError => "CERF_CONN_STATE_RECV_ERROR",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "CERF_CONN_STATE_UNKNOWN" => Some(Self::CerfConnStateUnknown),
                "CERF_CONN_STATE_CONNECTING" => Some(Self::CerfConnStateConnecting),
                "CERF_CONN_STATE_CONNECTED" => Some(Self::CerfConnStateConnected),
                "CERF_CONN_STATE_DISCONNECTED" => Some(Self::CerfConnStateDisconnected),
                "CERF_CONN_STATE_RECV_ERROR" => Some(Self::CerfConnStateRecvError),
                _ => None,
            }
        }
    }
}
/// IceEvent records ICE negotiation state changes.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct IceEvent {
    #[prost(enumeration = "ice_event::State", tag = "1")]
    pub state: i32,
    /// e.g. "host", "srflx", "relay"
    #[prost(string, tag = "2")]
    pub candidate_type: ::prost::alloc::string::String,
}
/// Nested message and enum types in `IceEvent`.
pub mod ice_event {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum State {
        IceStateUnknown = 0,
        IceStateChecking = 1,
        IceStateConnected = 2,
        IceStateCompleted = 3,
        IceStateFailed = 4,
        IceStateDisconnected = 5,
        IceStateClosed = 6,
    }
    impl State {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::IceStateUnknown => "ICE_STATE_UNKNOWN",
                Self::IceStateChecking => "ICE_STATE_CHECKING",
                Self::IceStateConnected => "ICE_STATE_CONNECTED",
                Self::IceStateCompleted => "ICE_STATE_COMPLETED",
                Self::IceStateFailed => "ICE_STATE_FAILED",
                Self::IceStateDisconnected => "ICE_STATE_DISCONNECTED",
                Self::IceStateClosed => "ICE_STATE_CLOSED",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "ICE_STATE_UNKNOWN" => Some(Self::IceStateUnknown),
                "ICE_STATE_CHECKING" => Some(Self::IceStateChecking),
                "ICE_STATE_CONNECTED" => Some(Self::IceStateConnected),
                "ICE_STATE_COMPLETED" => Some(Self::IceStateCompleted),
                "ICE_STATE_FAILED" => Some(Self::IceStateFailed),
                "ICE_STATE_DISCONNECTED" => Some(Self::IceStateDisconnected),
                "ICE_STATE_CLOSED" => Some(Self::IceStateClosed),
                _ => None,
            }
        }
    }
}
/// FilterEvent records packet filter decisions.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FilterEvent {
    #[prost(enumeration = "filter_event::Result", tag = "1")]
    pub result: i32,
    /// e.g. "no_matching_rule", "jailed", etc.
    #[prost(string, tag = "2")]
    pub reason: ::prost::alloc::string::String,
}
/// Nested message and enum types in `FilterEvent`.
pub mod filter_event {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum Result {
        FilterResultUnknown = 0,
        FilterResultAccept = 1,
        FilterResultDrop = 2,
    }
    impl Result {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::FilterResultUnknown => "FILTER_RESULT_UNKNOWN",
                Self::FilterResultAccept => "FILTER_RESULT_ACCEPT",
                Self::FilterResultDrop => "FILTER_RESULT_DROP",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "FILTER_RESULT_UNKNOWN" => Some(Self::FilterResultUnknown),
                "FILTER_RESULT_ACCEPT" => Some(Self::FilterResultAccept),
                "FILTER_RESULT_DROP" => Some(Self::FilterResultDrop),
                _ => None,
            }
        }
    }
}
/// PathTransitionEvent records when the active path changes.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PathTransitionEvent {
    #[prost(enumeration = "Transport", tag = "1")]
    pub from: i32,
    #[prost(enumeration = "Transport", tag = "2")]
    pub to: i32,
    /// e.g. "ice_connected", "cerf_fallback", etc.
    #[prost(string, tag = "3")]
    pub reason: ::prost::alloc::string::String,
}
/// GetEventsRequest is used to retrieve stored events.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetEventsRequest {
    #[prost(uint64, tag = "1")]
    pub node_id: u64,
    #[prost(string, tag = "2")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub from: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "4")]
    pub to: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(int32, tag = "5")]
    pub limit: i32,
    #[prost(int32, tag = "6")]
    pub offset: i32,
}
/// GetEventsResponse contains the retrieved events.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetEventsResponse {
    #[prost(message, repeated, tag = "1")]
    pub events: ::prost::alloc::vec::Vec<StoredOrbitEvent>,
    #[prost(int64, tag = "2")]
    pub total_count: i64,
}
/// StoredOrbitEvent is an event as stored in the database.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StoredOrbitEvent {
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(uint64, tag = "2")]
    pub node_id: u64,
    #[prost(string, tag = "3")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub client_version: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "5")]
    pub received_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "6")]
    pub event_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "7")]
    pub event_day: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(bytes = "vec", tag = "8")]
    pub peer_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag = "9")]
    pub region_id: u32,
    #[prost(enumeration = "Transport", tag = "10")]
    pub transport: i32,
    #[prost(string, tag = "11")]
    pub payload_type: ::prost::alloc::string::String,
    /// JSON-encoded payload
    #[prost(string, tag = "12")]
    pub payload: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "13")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
}
/// GetDailyCountsRequest is used to retrieve aggregated daily counts.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetDailyCountsRequest {
    #[prost(uint64, tag = "1")]
    pub node_id: u64,
    #[prost(string, tag = "2")]
    pub metric: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub from: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "4")]
    pub to: ::core::option::Option<::prost_types::Timestamp>,
}
/// GetDailyCountsResponse contains the aggregated counts.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetDailyCountsResponse {
    #[prost(message, repeated, tag = "1")]
    pub counts: ::prost::alloc::vec::Vec<DailyCount>,
}
/// DailyCount represents an aggregated count for a day.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DailyCount {
    #[prost(message, optional, tag = "1")]
    pub day: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag = "2")]
    pub node_id: u64,
    #[prost(string, tag = "3")]
    pub metric: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub label_key: ::prost::alloc::string::String,
    #[prost(int64, tag = "5")]
    pub count: i64,
    #[prost(message, optional, tag = "6")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "7")]
    pub updated_at: ::core::option::Option<::prost_types::Timestamp>,
}
/// Transport describes how a packet was sent/received.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Transport {
    Unknown = 0,
    Udp = 1,
    Ice = 2,
    Cerf = 3,
    CerfWs = 4,
}
impl Transport {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "TRANSPORT_UNKNOWN",
            Self::Udp => "TRANSPORT_UDP",
            Self::Ice => "TRANSPORT_ICE",
            Self::Cerf => "TRANSPORT_CERF",
            Self::CerfWs => "TRANSPORT_CERF_WS",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TRANSPORT_UNKNOWN" => Some(Self::Unknown),
            "TRANSPORT_UDP" => Some(Self::Udp),
            "TRANSPORT_ICE" => Some(Self::Ice),
            "TRANSPORT_CERF" => Some(Self::Cerf),
            "TRANSPORT_CERF_WS" => Some(Self::CerfWs),
            _ => None,
        }
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PingResponse {
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StunHost {
    #[prost(string, tag = "1")]
    pub url: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub password: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TurnHost {
    #[prost(string, tag = "1")]
    pub url: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub password: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RtcConfig {
    #[prost(message, optional, tag = "1")]
    pub turn_host: ::core::option::Option<TurnHost>,
    #[prost(message, optional, tag = "2")]
    pub stun_host: ::core::option::Option<StunHost>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetStunTurnConfigResponse {
    #[prost(message, optional, tag = "1")]
    pub rtc_config: ::core::option::Option<RtcConfig>,
}
include!("protos.tonic.rs");
// @@protoc_insertion_point(module)
